import { TextField } from "@mui/material";
import StateHoverTypeForm from "./StateHoverTypeForm";
import styles from "./ServiceFormContainer.module.css";

const ServiceFormContainer = () => {
  return (
    <div className={styles.services_group}>
      <StateHoverTypeForm
        stateHoverTypeFormBorder="4px dashed var(--gray)"
        stateHoverTypeFormWidth="474px"
        stateHoverTypeFormJustifyContent="flex-start"
        stateHoverTypeFormHeight="unset"
        stateHoverTypeFormCursor="unset"
        bFontSize="unset"
        bDisplay="unset"
        bAlignItems="unset"
        bJustifyContent="unset"
        bWidth="unset"
        bHeight="unset"
        bFlexShrink="unset"
        bAlignSelf="stretch"
        bFontFamily="unset"
        bColor="unset"
        bTextAlign="unset"
        bFontWeight="unset"
        addServiceFontSize="unset"
        addServiceAlignSelf="stretch"
        addServiceDisplay="unset"
        addServiceFontFamily="unset"
        addServiceColor="unset"
        addServiceTextAlign="unset"
        addServiceFontWeight="unset"
      />
      <StateHoverTypeForm
        stateHoverTypeFormBorder="4px dashed var(--gray)"
        stateHoverTypeFormWidth="474px"
        stateHoverTypeFormJustifyContent="flex-start"
        stateHoverTypeFormHeight="unset"
        stateHoverTypeFormCursor="unset"
        bFontSize="unset"
        bDisplay="unset"
        bAlignItems="unset"
        bJustifyContent="unset"
        bWidth="unset"
        bHeight="unset"
        bFlexShrink="unset"
        bAlignSelf="stretch"
        bFontFamily="unset"
        bColor="unset"
        bTextAlign="unset"
        bFontWeight="unset"
        addServiceFontSize="unset"
        addServiceAlignSelf="stretch"
        addServiceDisplay="unset"
        addServiceFontFamily="unset"
        addServiceColor="unset"
        addServiceTextAlign="unset"
        addServiceFontWeight="unset"
      />
      <StateHoverTypeForm
        stateHoverTypeFormBorder="4px dashed var(--gray)"
        stateHoverTypeFormWidth="474px"
        stateHoverTypeFormJustifyContent="flex-start"
        stateHoverTypeFormHeight="unset"
        stateHoverTypeFormCursor="unset"
        bFontSize="unset"
        bDisplay="unset"
        bAlignItems="unset"
        bJustifyContent="unset"
        bWidth="unset"
        bHeight="unset"
        bFlexShrink="unset"
        bAlignSelf="stretch"
        bFontFamily="unset"
        bColor="unset"
        bTextAlign="unset"
        bFontWeight="unset"
        addServiceFontSize="unset"
        addServiceAlignSelf="stretch"
        addServiceDisplay="unset"
        addServiceFontFamily="unset"
        addServiceColor="unset"
        addServiceTextAlign="unset"
        addServiceFontWeight="unset"
      />
      <StateHoverTypeForm
        prop="+"
        addService="Add Service"
        stateHoverTypeFormBorder="4px dashed var(--gray)"
        stateHoverTypeFormWidth="474px"
        stateHoverTypeFormJustifyContent="center"
        stateHoverTypeFormHeight="218px"
        stateHoverTypeFormCursor="unset"
        bFontSize="48px"
        bDisplay="flex"
        bAlignItems="center"
        bJustifyContent="center"
        bWidth="176px"
        bHeight="42px"
        bFlexShrink="0"
        bAlignSelf="unset"
        bFontFamily="'Fira Code'"
        bColor="#fff"
        bTextAlign="center"
        bFontWeight="unset"
        addServiceFontSize="20px"
        addServiceAlignSelf="unset"
        addServiceDisplay="inline-block"
        addServiceFontFamily="'Fira Code'"
        addServiceColor="#fff"
        addServiceTextAlign="center"
        addServiceFontWeight="unset"
        onServicesContainer3Click={onServicesContainer3Click}
      />
    </div>
  );
};

export default ServiceFormContainer;
